backend:
  name: github
  repo: bearceba/mccgov-cloudgov
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main

media_folder: assets/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Posts
    name: posts
    folder: _posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
  - label: Regions
    name: regions
    folder: _regions/
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'region'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Teaser", name: "regions_teaser", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - label: Countries
    name: country
    folder: _countries/
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'country'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Latitude", name: "country_latitude", widget: "string"}
      - {label: "Longitude", name: "country_longitude", widget: "string"}
      - {label: "ISO Two-Letter", name: "country_iso_two", widget: "string"}
      - {label: "ISO Three-Letter", name: "country_iso_three", widget: "string"}
